services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always

  api:
    build: ./backend
    image: fotsohub/api-orionattendance:latest
    container_name: attendance_api
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      PORT: 5000
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL:-https://attendance.horion.io}
    depends_on:
      - mongodb
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        # CRUCIAL : Remplace ceci par l'IP publique de ton serveur ou utilise un fichier .env
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://api-attendance.horion.io}
        - NEXT_PUBLIC_OFFICE_LAT=${NEXT_PUBLIC_OFFICE_LAT:-48.8566}
        - NEXT_PUBLIC_OFFICE_LNG=${NEXT_PUBLIC_OFFICE_LNG:-2.3522}
        - NEXT_PUBLIC_OFFICE_RADIUS_METERS=${NEXT_PUBLIC_OFFICE_RADIUS_METERS:-150}
    image: fotsohub/web-orionattendance:latest
    container_name: attendance_frontend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://api-attendance.horion.io}
      - NEXT_PUBLIC_OFFICE_LAT=${NEXT_PUBLIC_OFFICE_LAT:-48.8566}
      - NEXT_PUBLIC_OFFICE_LNG=${NEXT_PUBLIC_OFFICE_LNG:-2.3522}
      - NEXT_PUBLIC_OFFICE_RADIUS_METERS=${NEXT_PUBLIC_OFFICE_RADIUS_METERS:-150}
    depends_on:
      - api
    ports:
      - "127.0.0.1:3002:3000"
    networks:
      - app-network
    restart: always

  seeder:
    image: fotsohub/api-orionattendance:latest 
    container_name: attendance_seeder
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    command: node seedUsers.js 
    depends_on:
      mongodb:
        condition: service_started
    restart: "no" 
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge